services:
  web:
    image: karol3883/justcode:topgreen
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
      PORT: 80
