services:
  web:
    image: ${IMAGE_NAME:-ghcr.io/karol3883/topgreen:latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
